---
title: "t-SNE and barcoding gap analysis"
output: html_notebook
---

The "sp100_matrix" is the genetic distance matrix generated by Geneious for the subset of 100 species.

"sample_tax" is the taxonomy information dataframe, which has 9 columns:
seqid   taxid   kingdom   phylum    class   order   family    genus   species

## Input file
```{r}
sp100_matrix <- as.matrix(read.csv("sp100_distance.csv", row.names = 1))
sp100_df <- as.data.frame(as.table(as.matrix(sp100_matrix)))
colnames(sp100_df) <- c("Seq1", "Seq2", "Distance")
```

```{r}
sp100_dist <- as.dist(sp100_matrix)
```


## Barcoding gap calculation and visualization

```{r}
sp100_df2 <- merge(sp100_df, sample_tax, by.x="Seq1", by.y="seqid", all.x=TRUE)
sp100_df3 <- merge(sp100_df2, sample_tax, by.x="Seq2", by.y="seqid", all.x=TRUE)
colnames(sp100_df3) <- c("Seq2","Seq1","Distance","taxid1","kingdom1","phylum1","class1","order1","family1","genus1","species1","taxid2","kingdom2","phylum2","class2","order2","family2","genus2","species2")
```

```{r}
barcode_gap <- sp100_df3 %>% mutate(
        Type = ifelse(species1 == species2, "Intra-species", "Inter-species")) %>% filter(!is.na(Distance))
```


```{r}
ggplot(barcode_gap, aes(x = Distance, fill = Type)) +
    geom_density(alpha = 0.5) +
    scale_fill_manual(values = c("Intra-species" = "skyblue", "Inter-species" = "coral")) +
    labs(x = "Genetic Distance",
         y = "Density") +
    theme_bw()+theme(plot.background = element_rect(fill = "white", color = NA)) +scale_x_log10()
```



## t-SNE analysis

```{r}
sp100_tsne_result <- Rtsne(as.matrix(sp100_dist), is_distance = TRUE, perplexity = 30)
```

```{r}
sp100_tsne_df <- data.frame(X = sp100_tsne_result$Y[,1], 
                            Y = sp100_tsne_result$Y[,2], 
                            seqid = rownames(sp100_matrix))
sp100_tsne_df <- merge(sp100_tsne_df, sample_tax, by = "seqid", all.x=TRUE)
```

```{r}
ggplot(sp100_tsne_df, aes(x = X, y = Y, color = phylum)) +
    geom_point(alpha = 0.7, size = 2) +
    labs(title = "t-SNE of Sequence Distances", x = "t-SNE Dimension 1", y = "t-SNE Dimension 2") +
    theme_minimal() +
    theme(legend.position = "bottom", legend.text = element_text(size = 6)) +scale_color_observable()
```


